# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import time
from subprocess import call
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(438, 272)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 436, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tipsinfo1 = QtWidgets.QLabel(self.layoutWidget)
        self.tipsinfo1.setAlignment(QtCore.Qt.AlignCenter)
        self.tipsinfo1.setObjectName("tipsinfo1")
        self.horizontalLayout.addWidget(self.tipsinfo1)
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(self.layoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.tipsinfo = QtWidgets.QLabel(self.layoutWidget)
        self.tipsinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.tipsinfo.setObjectName("tipsinfo")
        self.gridLayout.addWidget(self.tipsinfo, 3, 0, 1, 1)
        self.runinfo1 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.runinfo1.setObjectName("runinfo1")
        self.gridLayout.addWidget(self.runinfo1, 2, 1, 1, 1)
        self.urllink = QtWidgets.QLabel(self.layoutWidget)
        self.urllink.setAlignment(QtCore.Qt.AlignCenter)
        self.urllink.setObjectName("urllink")
        self.gridLayout.addWidget(self.urllink, 0, 0, 1, 1)
        self.urllink1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.urllink1.setObjectName("urllink1")
        self.gridLayout.addWidget(self.urllink1, 0, 1, 1, 1)
        self.runinfo = QtWidgets.QLabel(self.layoutWidget)
        self.runinfo.setTabletTracking(False)
        self.runinfo.setTextFormat(QtCore.Qt.AutoText)
        self.runinfo.setAlignment(QtCore.Qt.AlignCenter)
        self.runinfo.setObjectName("runinfo")
        self.gridLayout.addWidget(self.runinfo, 2, 0, 1, 1)
        self.filename = QtWidgets.QLabel(self.layoutWidget)
        self.filename.setAlignment(QtCore.Qt.AlignCenter)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filename1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.filename1.setObjectName("filename1")
        self.horizontalLayout_7.addWidget(self.filename1)
        self.filename2 = QtWidgets.QLabel(self.layoutWidget)
        self.filename2.setObjectName("filename2")
        self.horizontalLayout_7.addWidget(self.filename2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.cancelButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.okButton.clicked.connect(self.callcmd)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "m3u8D"))
        self.tipsinfo1.setText(_translate("Dialog", "  "))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.cancelButton.setText(_translate("Dialog", "关闭"))
        self.tipsinfo.setText(_translate("Dialog", "提示"))
        self.urllink.setText(_translate("Dialog", "链接"))
        self.runinfo.setText(_translate("Dialog", "执行信息"))
        self.filename.setText(_translate("Dialog", "文件名"))
        self.filename2.setText(_translate("Dialog", ".mp4"))


    # def readtext(self):
    #     m3u8url = self.urllink1.text()
    #     filepath = self.filename1.text()+self.filename2.text()
    #     self.runinfo1.append(filepath+'正在下载中,请稍后...')
    #     time.sleep(10)
    #     self.runinfo1.append(filepath+'下载完成.'+'\n文件保存在download目录下!')
    #     font = QtGui.QFont()
    #     font.setFamily("微软雅黑")
    #     font.setPointSize(10)
    #     self.tipsinfo1.setFont(font)
    #     self.tipsinfo1.setText('下载成功!')

    def callcmd(self):
        # 调用cmd执行ffmpeg程序
        m3u8url = self.urllink1.text()
        filepath = self.filename1.text()+self.filename2.text()
        self.runinfo1.append(filepath+'正在下载中,请稍后...')
        cmd ='./ffmpeg/bin/ffmpeg -i '+m3u8url +' ./download/'+filepath
        call(cmd, shell=False)
        self.runinfo1.setText(filepath+'下载完成.'+'\n文件保存在download目录下!')
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.tipsinfo1.setFont(font)
        self.tipsinfo1.setText('下载成功!')
